---
name: AutoSell
main: MCA7\AutoSell\Main
author: MCA7
api: 5.0.0
version: 3.1.2
website: https://github.com/MCPEAbdu77/AutoSellPE
softdepend:
  - BedrockEconomy
  - EconomyAPI
  - Capital

commands:
  autosell:
    description: "/autosell < on | off | add | remove | view >"
    aliases: [ as ]
    permission: autosell.command

permissions:
  autosell.command:
    description: "Gives the user the permission to use /autosell < ON / OFF >"
    default: op
  autosell.command.add:
    default: op
  autosell.command.remove:
    default: op
  autosell.command.view:
    default: true
    # op - allow only users with 'autosell.command' to use AutoSell
    # true - allow everyone by default
...
