---
# AutoSell by MCA7#1245
name: AutoSell
main: MCA7\AutoSell\Main
api: 3.18.0
load: POSTWORLD
version: 2.2.0
depend: EconomyAPI

commands:
  autosell:
    description: "Usage: /autosell <on/off>"
    aliases: [as]
    permission: autosell.command

permissions:
  autosell.command:
    description: "Gives the user the permission to use /autosell"
    default: op
    # change default to 'op' if you want it to work only for those
    # with the 'autosell.command' permission.
...
